### ISSUE TITLE
Support for static templates

### ISSUE THREAD

**Issue by zeekay** [aMarCruz/gen-pug-source-map#2]
How much work would it be to add support for source maps for static templates?

**Comment by aMarCruz** [comment]
@zeekay sorry by the delay.
It is a medium work, but neither Pug nor the sourceMap specs offer facilities for pure HTML (maybe because it doesn't have much use). On the other hand I am currently focusing on React Native and I have very little time to maintain this plugin so I do not plan to add new features, but I'll try to keep it updated.

Of course a PR is welcome.
Closing this now.
